/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/coffee.glb -o src/components/CoffeeModel.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coffee.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tmpa_oire0gobj.geometry} material={materials.pbr_material} position={[0.023, 0.022, 0.015]} scale={0.548} />
    </group>
  )
}

useGLTF.preload('/coffee.glb')
